name: Deploy to Remote Server

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag) to deploy'
        required: false
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script
        env:
          REF: ${{ inputs.ref }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          PORT: ${{ secrets.PORT }}
          GOOGLE_OAUTH2_CREDS: ${{ secrets.GOOGLE_OAUTH2_CREDS}}
          ORIGIN: ${{ secrets.ORIGIN }}
          ORIGIN_API: ${{ secrets.ORIGIN_API }}
          POSTGRES_CONN_JSON: ${{ secrets.POSTGRES_CONN_JSON }}
          SESSION_TTL_SEC: ${{ secrets.SESSION_TTL_SEC }}
        run: |
          chmod +x ./ops/deploy.sh
          ./ops/deploy.sh

